name: Pull Request Workflow

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies and run tests
        run: |
          npm install
          npm run test
          npx cypress open --env type=base
