name: Pull Request Workflow

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Certifique-se de que o Node.js 14 é compatível com o Angular que você está usando

      - name: Install dependencies
        run: npm install

      - name: Install build
        run: npm build

      - name: Install test
        run: npm test --if-present
